default_model: 'anthropic/claude-3-5-sonnet-20240620'
log_level: 'INFO'
log_file: '{{ user_dir }}/repoai.log'
max_log_file_size: 10485760  # 10 MB
log_backup_count: 5
max_commit_history: 10
docker_compose_file: 'docker-compose.yml'
global_token_usage_file: '{{ user_dir }}/global_token_usage.json'
project_token_usage_file: '{{ repoai_dir }}/token_usage.json'
repoai_ignore_file: '{{ repoai_dir }}/.repoaiignore'
prompt_cache_threshold: 20000
plugin_dir: '{{ user_dir }}/plugins'